version: '3.8'
services:
  webapplication2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=WebApplication2Db;User=sa;Password=Your_password123;
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"